### ISSUE TITLE
Assiging new roles to `static/images/roles` pictures.

### ISSUE THREAD

**Issue by sadrasabouri** [sadrasabouri/mafia#1]
**Is your feature request related to a problem? Please describe.**
Perhaps we'll need more than one image for each role so we should assign any of our images to a specific mafia role.
We should have <b>at least</b> roles:
+ Resident / شهروند
+ Mafia / مافیا
+ Don / دن
+ Doctor / دکتر
+ Rebel / شورشی
+ Anti-attack / ضد ضربه
+ Detective / کارآگاه

adding any other role would be appreciated by us, so please feel free about commenting your favorite role in this issue.

**Describe the solution you'd like**
For adding this feature one should:
1. rename each `.png` image in `static/images/roles`
2. Update `nroles` in `mafia_params.py`
3. then declare this assignment in `README.md` file in <b><i>Roles</i></b> section as before declarations.
The format that I've used for assigning so far is like this:
```
[role_name]_[index].png
```
For example: Doctor_1.png, Doctor_2.png and so on.

**Comment by annahiidd** [comment]
Anti attack 🙅🏻‍♀️
Bulletproof 💁🏻‍♀️😂

**Comment by sadrasabouri** [comment]
> Anti attack 🙅🏻‍♀️
> Bulletproof 💁🏻‍♀️joy

Thank you for your comment.
I handled it in [this](https://github.com/sadrasabouri/mafia/commit/30c1d9ed7d42958dae523e524b9faed5635a2e0d) commit.

**Comment by sadrasabouri** [comment]
New roles will be added:

Residents team:

+ Judge/قاضی
+ Insane/دیوانه
+ Boxer/بوکسور
+ Jailer/زندان بان
+ Bride/داماد
+ Groom/عروس
+ Curious Kid/کودک کنجکاور
+ Miller/آسیابان
+ Bus Driver/راننده اتوبوس
+ Chef
+ Postman/پستچی
+ Genie/غول
+ Grandma/مادربزرگ
+ Magician/شعبده باز
+ Undercover Cop/پلیس مخفی
+ Student/دانش آموز

Mafia team:
+ Lawyer/وکیل
+ Made Man/آدم اجیر کن
+ Kind Wife/همسر مهربان
