### ISSUE TITLE
Role Descriptions

### ISSUE THREAD

**Issue by sadrasabouri** [sadrasabouri/mafia#3]
**Is your feature request related to a problem? Please describe.**
We have 6 type of roles in the game till now.
Each of them wants it's unique description about ability it has in either day or night mode.

**Describe the solution you'd like**
+ Add your description to `description` dictionary about each role in `mafia_params.py`
    - Add it's persian translation to its Farsi alternative `description_fa` in `mafia_params.py`
+ Add these descriptions to new column in roles table in `README.md`.
+ If you are using any references add it to <b>References</b> section in `README.md`.

**Comment by annahiidd** [comment]
دُن:
اين نقش سردسته تيم مافيا ميباشد و مسئوليت تيم مافيا بر عهده دُن است.
امتياز حائز اهميتی که دُن در بازی دارد اين است که استعلامش توسط کاراگاه همانند شهروندان منفی میباشد.

**Comment by annahiidd** [comment]
مافيا:
از اعضای تیم مافیا میباشد و اگر کاراگاه از او استعلام بگیرد، استعلامش مثبت در میاید.

**Comment by annahiidd** [comment]
دکتر :
دکتر يکی از اعضای تیم شهروند ميباشد که در فاز شب به فرمان خدای بازی چشم هايش را باز کرده و ميتواند خود و يا يکی از بازيکنان را از حذف شدن و کشته شدن در فاز شب بازی نجات دهد.

**Comment by annahiidd** [comment]
کاراگاه :
کاراگاه يکی از اعضای تیم شهروند ميباشد که در فاز شب چشم هايش را باز کرده و ميتواند از خدای بازی هويت يکی از افراد بازی را بپرسد ، و خدا با اشاره بله يا خیر به کاراگاه ميگويد که فرد استعلام شده جزو اعضای مافيا هست يا نه

**Comment by annahiidd** [comment]
ضد ضربه:
ضد ضربه قوی ترين شهروند بازی ميباشد ،و از هر تير مافیا در فاز شب در امان ميباشد.
بنابرين ضد ضربه توسط مافيا در فاز شب قابل کشته شدن نميباشد .

**Comment by annahiidd** [comment]
شورشی:
از اعضای تیم شهروند میباشد و در فاز شب میتواند کسی را که فکر میکند مافیا است را هدف قرار دهد
اگر شخص مافیا بود خواهد مرد.
اما اگر شورشی به اشتباه یک شهروند را هدف قرار دهد خودش خواهد مرد.
